#!/bin/sh

rm files/root/INSTALLED_PACKAGES
printf "$(ls packages/base)\n$(ls packages/tools)\n$(ls packages/xorg)\n$(ls packages/xapps)" > files/root/INSTALLED_PACKAGES
cp files/root/INSTALLED_PACKAGES PACKAGES.txt
chown 1000:1000 PACKAGES.txt
