#!/bin/sh

. files/etc/os-release

echo
echo "Now making ISO bootable image..."
echo

printf "[iso] Checking if old cdroot directory is available..."
if [ -d ${PWD}/cdroot ]; then
	printf "yes, deleting...\n"
	rm -rf cdroot
else
	printf "no\n"
fi

printf "[iso] Checking if old distrb directory is available..."
if [ -d ${PWD}/distrb ]; then
	printf "yes, deleting...\n"
	rm -rf distrb
else
	printf "no\n"
fi

if [ ! -d "cdroot" ]; then
	echo "[iso] Creating cdroot directory..."
	mkdir -pv cdroot/boot
	mkdir -v cdroot/isolinux
fi

echo "[iso] Copying boot media contents into cdroot directory..."
cp -rv syslinux/$(uname -m)-BIOS/* cdroot/isolinux
cp -v rootfs.gz cdroot/boot
cp -v vmlinuz cdroot/boot

if [ ! -d "distrb" ]; then
	echo "[iso] Creating distrb directory..."
	mkdir -v distrb
fi

echo "[iso] Creating ISO9660 bootable image..."
xorriso \
	-as mkisofs \
    -iso-level 3 \
    -full-iso9660-filenames \
    -volid "ANMINCAT" \
    -eltorito-boot \
    isolinux/isolinux.bin \
    -no-emul-boot \
    -boot-load-size 4 \
    -boot-info-table \
    --eltorito-catalog isolinux/isolinux.cat \
    -output "${PWD}/distrb/Anmincat_$VERSION_ID.iso" \
        "${PWD}/cdroot"

echo "[iso] Applying isohybrid..."
isohybrid distrb/Anmincat_$VERSION_ID.iso

echo "[iso] Calculating md5..."
md5sum distrb/Anmincat_$VERSION_ID.iso > distrb/MD5SUM.txt
cat distrb/MD5SUM.txt

echo "[iso] Calculating sha1sum..."
sha1sum distrb/Anmincat_$VERSION_ID.iso > distrb/SHA1SUM.txt
cat distrb/SHA1SUM.txt

echo "[iso] Calculating sha256..."
sha256sum distrb/Anmincat_$VERSION_ID.iso > distrb/SHA256SUM.txt
cat distrb/SHA256SUM.txt

echo "[iso] Copying files/root/INSTALLED_PACKAGES to PACKAGES.txt..."
cp -rv files/root/PACKAGES distrb/PACKAGES.txt
chown 1000:1000 distrb/PACKAGES.txt
chown 1000:1000 distrb/Anmincat_$VERSION_ID.iso
chown 1000:1000 distrb/MD5SUM.txt
chown 1000:1000 distrb/SHA1SUM.txt
chown 1000:1000 distrb/SHA256SUM.txt

echo "[iso] Finished!"
